version: "2"
services:
  archive:
    build: .
    environment:
      - DB_USER=cnxarchive
      - DB_NAME=cnxarchive-testing
      - DB_HOST=db
      - MEMCACHE_SERVERS=memcached
    volumes:
      - ./.git:/src/.git
    ports:
      - "6543:6543"
    links:
      - db
      - memcached
  db:
    # image: openstax/cnx-db:2.3.0
    build:
      context: https://github.com/Connexions/cnx-db.git
    ports:
      - "5433:5432"
    environment:
      - "DB_USER=cnxarchive"
      - "POSTGRES_DB=cnxarchive-testing"
      - "DB_URL=postgresql://cnxarchive@/cnxarchive-testing"
      - "DB_SUPER_URL=postgresql://postgres@/cnxarchive-testing"
  memcached:
    image: memcached:1.5
    ports:
      - "11211"
