version: "3"
services:

  archive:
    build: .
    volumes:
      # This mounts this project into the container for development use.
      - ./cnxarchive:/src/cnxarchive:z
      - ./development.ini:/src/development.ini
      - ./docs:/src/docs
      - ./LICENSE.txt:/src/LICENSE.txt
      - ./MANIFEST.in:/src/MANIFEST.in
      - ./README.rst:/src/README.rst
      - ./setup.cfg:/src/setup.cfg
      - ./setup.py:/src/setup.py
      - ./versioneer.py:/src/versioneer.py
    ports:
      # Allows you to access the application at http://localhost:6543.
      - "6543:6543"
    environment:
      # Use the docker aware version of the testing configuration file
      - TESTING_CONFIG=cnxarchive/tests/docker-testing.ini

  db:
    image: openstax/cnx-db:3.5.3
    ports:
      # Exposes the port to a random external port number.
      # Use `docker ps` to find the external port mapping.
      - "5432"
    # If you'd like to load the database with data, have a look at:
    # https://github.com/Connexions/devops/wiki/How-To%3A-Get-a-Slim-Database-Dump
    # But do keep in mind that it will be wiped away if you are
    # also running the unit tests

  memcached:
    image: memcached:1.5
