version: "2"
services:
  archive:
    build: .
    ports:
      - "6543:6543"
    links:
      - db
      - memcached
  db:
    image: openstax/cnx-db:1.5.1
    ports:
      - "5432"
#    volumes:
      # https://github.com/Connexions/devops/wiki/How-To%3A-Get-a-Slim-Database-Dump
  memcached:
    image: memcached:1.5
    ports:
      - "11211"
